#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<EOF
  CREATE DATABASE hydra;
  CREATE DATABASE komadori;

  CREATE USER hydra WITH PASSWORD '${HYDRA_DB_PASSWORD}';
  CREATE USER komadori WITH PASSWORD '${KOMADORI_DB_PASSWORD}';

  GRANT ALL PRIVILEGES ON DATABASE hydra TO hydra;
  GRANT ALL PRIVILEGES ON DATABASE komadori TO komadori;
  ALTER USER komadori WITH SUPERUSER;
EOF
