/* 
 * Hydra OAuth2 & OpenID Connect Server
 *
 * Please refer to the user guide for in-depth documentation: https://ory.gitbooks.io/hydra/content/   Hydra offers OAuth 2.0 and OpenID Connect Core 1.0 capabilities as a service. Hydra is different, because it works with any existing authentication infrastructure, not just LDAP or SAML. By implementing a consent app (works with any programming language) you build a bridge between Hydra and your authentication infrastructure. Hydra is able to securely manage JSON Web Keys, and has a sophisticated policy-based access control you can use if you want to. Hydra is suitable for green- (new) and brownfield (existing) projects. If you are not familiar with OAuth 2.0 and are working on a greenfield project, we recommend evaluating if OAuth 2.0 really serves your purpose. Knowledge of OAuth 2.0 is imperative in understanding what Hydra does and how it works.   The official repository is located at https://github.com/ory/hydra   ### Important REST API Documentation Notes  The swagger generator used to create this documentation does currently not support example responses. To see request and response payloads click on **\"Show JSON schema\"**: ![Enable JSON Schema on Apiary](https://storage.googleapis.com/ory.am/hydra/json-schema.png)   The API documentation always refers to the latest tagged version of ORY Hydra. For previous API documentations, please refer to https://github.com/ory/hydra/blob/<tag-id>/docs/api.swagger.yaml - for example:  0.9.13: https://github.com/ory/hydra/blob/v0.9.13/docs/api.swagger.yaml 0.8.1: https://github.com/ory/hydra/blob/v0.8.1/docs/api.swagger.yaml
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ConsentRequestAcceptance {
  /// AccessTokenExtra represents arbitrary data that will be added to the access token and that will be returned on introspection and warden requests.
  #[serde(rename = "accessTokenExtra")]
  access_token_extra: Option<::std::collections::HashMap<String, Value>>,
  /// AuthTime is the time when the End-User authentication occurred. Its value is a JSON number representing the number of seconds from 1970-01-01T0:0:0Z as measured in UTC until the date/time.
  #[serde(rename = "authTime")]
  auth_time: Option<i64>,
  /// A list of scopes that the user agreed to grant. It should be a subset of requestedScopes from the consent request.
  #[serde(rename = "grantScopes")]
  grant_scopes: Option<Vec<String>>,
  /// IDTokenExtra represents arbitrary data that will be added to the ID token. The ID token will only be issued if the user agrees to it and if the client requested an ID token.
  #[serde(rename = "idTokenExtra")]
  id_token_extra: Option<::std::collections::HashMap<String, Value>>,
  /// ProvidedAuthenticationContextClassReference specifies an Authentication Context Class Reference value that identifies the Authentication Context Class that the authentication performed satisfied. The value \"0\" indicates the End-User authentication did not meet the requirements of ISO/IEC 29115 [ISO29115] level 1.  In summary ISO/IEC 29115 defines four levels, broadly summarized as follows.  acr=0 does not satisfy Level 1 and could be, for example, authentication using a long-lived browser cookie. Level 1 (acr=1): Minimal confidence in the asserted identity of the entity, but enough confidence that the entity is the same over consecutive authentication events. For example presenting a self-registered username or password. Level 2 (acr=2): There is some confidence in the asserted identity of the entity. For example confirming authentication using a mobile app (\"Something you have\"). Level 3 (acr=3): High confidence in an asserted identity of the entity. For example sending a code to a mobile phone or using Google Authenticator or a fingerprint scanner (\"Something you have and something you know\" / \"Something you are\") Level 4 (acr=4): Very high confidence in an asserted identity of the entity. Requires in-person identification.
  #[serde(rename = "providedAcr")]
  provided_acr: Option<String>,
  /// Subject represents a unique identifier of the user (or service, or legal entity, ...) that accepted the OAuth2 request.
  #[serde(rename = "subject")]
  subject: Option<String>
}

impl ConsentRequestAcceptance {
  pub fn new() -> ConsentRequestAcceptance {
    ConsentRequestAcceptance {
      access_token_extra: None,
      auth_time: None,
      grant_scopes: None,
      id_token_extra: None,
      provided_acr: None,
      subject: None
    }
  }

  pub fn set_access_token_extra(&mut self, access_token_extra: ::std::collections::HashMap<String, Value>) {
    self.access_token_extra = Some(access_token_extra);
  }

  pub fn with_access_token_extra(mut self, access_token_extra: ::std::collections::HashMap<String, Value>) -> ConsentRequestAcceptance {
    self.access_token_extra = Some(access_token_extra);
    self
  }

  pub fn access_token_extra(&self) -> Option<&::std::collections::HashMap<String, Value>> {
    self.access_token_extra.as_ref()
  }

  pub fn reset_access_token_extra(&mut self) {
    self.access_token_extra = None;
  }

  pub fn set_auth_time(&mut self, auth_time: i64) {
    self.auth_time = Some(auth_time);
  }

  pub fn with_auth_time(mut self, auth_time: i64) -> ConsentRequestAcceptance {
    self.auth_time = Some(auth_time);
    self
  }

  pub fn auth_time(&self) -> Option<&i64> {
    self.auth_time.as_ref()
  }

  pub fn reset_auth_time(&mut self) {
    self.auth_time = None;
  }

  pub fn set_grant_scopes(&mut self, grant_scopes: Vec<String>) {
    self.grant_scopes = Some(grant_scopes);
  }

  pub fn with_grant_scopes(mut self, grant_scopes: Vec<String>) -> ConsentRequestAcceptance {
    self.grant_scopes = Some(grant_scopes);
    self
  }

  pub fn grant_scopes(&self) -> Option<&Vec<String>> {
    self.grant_scopes.as_ref()
  }

  pub fn reset_grant_scopes(&mut self) {
    self.grant_scopes = None;
  }

  pub fn set_id_token_extra(&mut self, id_token_extra: ::std::collections::HashMap<String, Value>) {
    self.id_token_extra = Some(id_token_extra);
  }

  pub fn with_id_token_extra(mut self, id_token_extra: ::std::collections::HashMap<String, Value>) -> ConsentRequestAcceptance {
    self.id_token_extra = Some(id_token_extra);
    self
  }

  pub fn id_token_extra(&self) -> Option<&::std::collections::HashMap<String, Value>> {
    self.id_token_extra.as_ref()
  }

  pub fn reset_id_token_extra(&mut self) {
    self.id_token_extra = None;
  }

  pub fn set_provided_acr(&mut self, provided_acr: String) {
    self.provided_acr = Some(provided_acr);
  }

  pub fn with_provided_acr(mut self, provided_acr: String) -> ConsentRequestAcceptance {
    self.provided_acr = Some(provided_acr);
    self
  }

  pub fn provided_acr(&self) -> Option<&String> {
    self.provided_acr.as_ref()
  }

  pub fn reset_provided_acr(&mut self) {
    self.provided_acr = None;
  }

  pub fn set_subject(&mut self, subject: String) {
    self.subject = Some(subject);
  }

  pub fn with_subject(mut self, subject: String) -> ConsentRequestAcceptance {
    self.subject = Some(subject);
    self
  }

  pub fn subject(&self) -> Option<&String> {
    self.subject.as_ref()
  }

  pub fn reset_subject(&mut self) {
    self.subject = None;
  }

}



