/* 
 * ORY Hydra - Cloud Native OAuth 2.0 and OpenID Connect Server
 *
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here. Keep in mind that this document reflects the latest branch, always. Support for versioned documentation is coming in the future.
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct FlushInactiveOAuth2TokensRequest {
  /// NotAfter sets after which point tokens should not be flushed. This is useful when you want to keep a history of recently issued tokens for auditing.
  #[serde(rename = "notAfter")]
  not_after: Option<String>
}

impl FlushInactiveOAuth2TokensRequest {
  pub fn new() -> FlushInactiveOAuth2TokensRequest {
    FlushInactiveOAuth2TokensRequest {
      not_after: None
    }
  }

  pub fn set_not_after(&mut self, not_after: String) {
    self.not_after = Some(not_after);
  }

  pub fn with_not_after(mut self, not_after: String) -> FlushInactiveOAuth2TokensRequest {
    self.not_after = Some(not_after);
    self
  }

  pub fn not_after(&self) -> Option<&String> {
    self.not_after.as_ref()
  }

  pub fn reset_not_after(&mut self) {
    self.not_after = None;
  }

}



