/* 
 * Hydra OAuth2 & OpenID Connect Server
 *
 * Please refer to the user guide for in-depth documentation: https://ory.gitbooks.io/hydra/content/   Hydra offers OAuth 2.0 and OpenID Connect Core 1.0 capabilities as a service. Hydra is different, because it works with any existing authentication infrastructure, not just LDAP or SAML. By implementing a consent app (works with any programming language) you build a bridge between Hydra and your authentication infrastructure. Hydra is able to securely manage JSON Web Keys, and has a sophisticated policy-based access control you can use if you want to. Hydra is suitable for green- (new) and brownfield (existing) projects. If you are not familiar with OAuth 2.0 and are working on a greenfield project, we recommend evaluating if OAuth 2.0 really serves your purpose. Knowledge of OAuth 2.0 is imperative in understanding what Hydra does and how it works.   The official repository is located at https://github.com/ory/hydra   ### Important REST API Documentation Notes  The swagger generator used to create this documentation does currently not support example responses. To see request and response payloads click on **\"Show JSON schema\"**: ![Enable JSON Schema on Apiary](https://storage.googleapis.com/ory.am/hydra/json-schema.png)   The API documentation always refers to the latest tagged version of ORY Hydra. For previous API documentations, please refer to https://github.com/ory/hydra/blob/<tag-id>/docs/api.swagger.yaml - for example:  0.9.13: https://github.com/ory/hydra/blob/v0.9.13/docs/api.swagger.yaml 0.8.1: https://github.com/ory/hydra/blob/v0.8.1/docs/api.swagger.yaml
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Handler {
  #[serde(rename = "Generators")]
  generators: Option<::std::collections::HashMap<String, ::models::KeyGenerator>>,
  #[serde(rename = "H")]
  H: Option<::models::Writer>,
  #[serde(rename = "Manager")]
  manager: Option<::models::Manager>,
  #[serde(rename = "ResourcePrefix")]
  resource_prefix: Option<String>,
  #[serde(rename = "W")]
  W: Option<::models::Firewall>
}

impl Handler {
  pub fn new() -> Handler {
    Handler {
      generators: None,
      H: None,
      manager: None,
      resource_prefix: None,
      W: None
    }
  }

  pub fn set_generators(&mut self, generators: ::std::collections::HashMap<String, ::models::KeyGenerator>) {
    self.generators = Some(generators);
  }

  pub fn with_generators(mut self, generators: ::std::collections::HashMap<String, ::models::KeyGenerator>) -> Handler {
    self.generators = Some(generators);
    self
  }

  pub fn generators(&self) -> Option<&::std::collections::HashMap<String, ::models::KeyGenerator>> {
    self.generators.as_ref()
  }

  pub fn reset_generators(&mut self) {
    self.generators = None;
  }

  pub fn set_H(&mut self, H: ::models::Writer) {
    self.H = Some(H);
  }

  pub fn with_H(mut self, H: ::models::Writer) -> Handler {
    self.H = Some(H);
    self
  }

  pub fn H(&self) -> Option<&::models::Writer> {
    self.H.as_ref()
  }

  pub fn reset_H(&mut self) {
    self.H = None;
  }

  pub fn set_manager(&mut self, manager: ::models::Manager) {
    self.manager = Some(manager);
  }

  pub fn with_manager(mut self, manager: ::models::Manager) -> Handler {
    self.manager = Some(manager);
    self
  }

  pub fn manager(&self) -> Option<&::models::Manager> {
    self.manager.as_ref()
  }

  pub fn reset_manager(&mut self) {
    self.manager = None;
  }

  pub fn set_resource_prefix(&mut self, resource_prefix: String) {
    self.resource_prefix = Some(resource_prefix);
  }

  pub fn with_resource_prefix(mut self, resource_prefix: String) -> Handler {
    self.resource_prefix = Some(resource_prefix);
    self
  }

  pub fn resource_prefix(&self) -> Option<&String> {
    self.resource_prefix.as_ref()
  }

  pub fn reset_resource_prefix(&mut self) {
    self.resource_prefix = None;
  }

  pub fn set_W(&mut self, W: ::models::Firewall) {
    self.W = Some(W);
  }

  pub fn with_W(mut self, W: ::models::Firewall) -> Handler {
    self.W = Some(W);
    self
  }

  pub fn W(&self) -> Option<&::models::Firewall> {
    self.W.as_ref()
  }

  pub fn reset_W(&mut self) {
    self.W = None;
  }

}



