/* 
 * ORY Hydra - Cloud Native OAuth 2.0 and OpenID Connect Server
 *
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here. Keep in mind that this document reflects the latest branch, always. Support for versioned documentation is coming in the future.
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct JoseWebKeySetRequest {
  #[serde(rename = "keys")]
  keys: Option<Vec<::models::RawMessage>>
}

impl JoseWebKeySetRequest {
  pub fn new() -> JoseWebKeySetRequest {
    JoseWebKeySetRequest {
      keys: None
    }
  }

  pub fn set_keys(&mut self, keys: Vec<::models::RawMessage>) {
    self.keys = Some(keys);
  }

  pub fn with_keys(mut self, keys: Vec<::models::RawMessage>) -> JoseWebKeySetRequest {
    self.keys = Some(keys);
    self
  }

  pub fn keys(&self) -> Option<&Vec<::models::RawMessage>> {
    self.keys.as_ref()
  }

  pub fn reset_keys(&mut self) {
    self.keys = None;
  }

}



