/* 
 * ORY Hydra - Cloud Native OAuth 2.0 and OpenID Connect Server
 *
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here. Keep in mind that this document reflects the latest branch, always. Support for versioned documentation is coming in the future.
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct JsonWebKeySetGeneratorRequest {
  /// The algorithm to be used for creating the key. Supports \"RS256\", \"ES512\", \"HS512\", and \"HS256\"
  #[serde(rename = "alg")]
  alg: String,
  /// The kid of the key to be created
  #[serde(rename = "kid")]
  kid: String
}

impl JsonWebKeySetGeneratorRequest {
  pub fn new(alg: String, kid: String) -> JsonWebKeySetGeneratorRequest {
    JsonWebKeySetGeneratorRequest {
      alg: alg,
      kid: kid
    }
  }

  pub fn set_alg(&mut self, alg: String) {
    self.alg = alg;
  }

  pub fn with_alg(mut self, alg: String) -> JsonWebKeySetGeneratorRequest {
    self.alg = alg;
    self
  }

  pub fn alg(&self) -> &String {
    &self.alg
  }


  pub fn set_kid(&mut self, kid: String) {
    self.kid = kid;
  }

  pub fn with_kid(mut self, kid: String) -> JsonWebKeySetGeneratorRequest {
    self.kid = kid;
    self
  }

  pub fn kid(&self) -> &String {
    &self.kid
  }


}



