/* 
 * ORY Hydra - Cloud Native OAuth 2.0 and OpenID Connect Server
 *
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here. Keep in mind that this document reflects the latest branch, always. Support for versioned documentation is coming in the future.
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct JsonWebKeySet {
  /// The value of the \"keys\" parameter is an array of JWK values.  By default, the order of the JWK values within the array does not imply an order of preference among them, although applications of JWK Sets can choose to assign a meaning to the order for their purposes, if desired.
  #[serde(rename = "keys")]
  keys: Option<Vec<::models::JsonWebKey>>
}

impl JsonWebKeySet {
  pub fn new() -> JsonWebKeySet {
    JsonWebKeySet {
      keys: None
    }
  }

  pub fn set_keys(&mut self, keys: Vec<::models::JsonWebKey>) {
    self.keys = Some(keys);
  }

  pub fn with_keys(mut self, keys: Vec<::models::JsonWebKey>) -> JsonWebKeySet {
    self.keys = Some(keys);
    self
  }

  pub fn keys(&self) -> Option<&Vec<::models::JsonWebKey>> {
    self.keys.as_ref()
  }

  pub fn reset_keys(&mut self) {
    self.keys = None;
  }

}



