/* 
 * ORY Hydra - Cloud Native OAuth 2.0 and OpenID Connect Server
 *
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here. Keep in mind that this document reflects the latest branch, always. Support for versioned documentation is coming in the future.
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct SwaggerRejectConsentRequest {
  #[serde(rename = "Body")]
  body: ::models::ConsentRequestRejection,
  /// in: path
  #[serde(rename = "id")]
  id: String
}

impl SwaggerRejectConsentRequest {
  pub fn new(body: ::models::ConsentRequestRejection, id: String) -> SwaggerRejectConsentRequest {
    SwaggerRejectConsentRequest {
      body: body,
      id: id
    }
  }

  pub fn set_body(&mut self, body: ::models::ConsentRequestRejection) {
    self.body = body;
  }

  pub fn with_body(mut self, body: ::models::ConsentRequestRejection) -> SwaggerRejectConsentRequest {
    self.body = body;
    self
  }

  pub fn body(&self) -> &::models::ConsentRequestRejection {
    &self.body
  }


  pub fn set_id(&mut self, id: String) {
    self.id = id;
  }

  pub fn with_id(mut self, id: String) -> SwaggerRejectConsentRequest {
    self.id = id;
    self
  }

  pub fn id(&self) -> &String {
    &self.id
  }


}



