/* 
 * ORY Hydra - Cloud Native OAuth 2.0 and OpenID Connect Server
 *
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here. Keep in mind that this document reflects the latest branch, always. Support for versioned documentation is coming in the future.
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct SwaggerOAuthConsentRequestPayload {
  /// The id of the OAuth 2.0 Consent Request.
  #[serde(rename = "id")]
  id: String
}

impl SwaggerOAuthConsentRequestPayload {
  pub fn new(id: String) -> SwaggerOAuthConsentRequestPayload {
    SwaggerOAuthConsentRequestPayload {
      id: id
    }
  }

  pub fn set_id(&mut self, id: String) {
    self.id = id;
  }

  pub fn with_id(mut self, id: String) -> SwaggerOAuthConsentRequestPayload {
    self.id = id;
    self
  }

  pub fn id(&self) -> &String {
    &self.id
  }


}



