/* 
 * ORY Hydra - Cloud Native OAuth 2.0 and OpenID Connect Server
 *
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here. Keep in mind that this document reflects the latest branch, always. Support for versioned documentation is coming in the future.
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct SwaggerJwkUpdateSetKey {
  #[serde(rename = "Body")]
  body: Option<::models::JsonWebKey>,
  /// The kid of the desired key in: path
  #[serde(rename = "kid")]
  kid: String,
  /// The set in: path
  #[serde(rename = "set")]
  set: String
}

impl SwaggerJwkUpdateSetKey {
  pub fn new(kid: String, set: String) -> SwaggerJwkUpdateSetKey {
    SwaggerJwkUpdateSetKey {
      body: None,
      kid: kid,
      set: set
    }
  }

  pub fn set_body(&mut self, body: ::models::JsonWebKey) {
    self.body = Some(body);
  }

  pub fn with_body(mut self, body: ::models::JsonWebKey) -> SwaggerJwkUpdateSetKey {
    self.body = Some(body);
    self
  }

  pub fn body(&self) -> Option<&::models::JsonWebKey> {
    self.body.as_ref()
  }

  pub fn reset_body(&mut self) {
    self.body = None;
  }

  pub fn set_kid(&mut self, kid: String) {
    self.kid = kid;
  }

  pub fn with_kid(mut self, kid: String) -> SwaggerJwkUpdateSetKey {
    self.kid = kid;
    self
  }

  pub fn kid(&self) -> &String {
    &self.kid
  }


  pub fn set_set(&mut self, set: String) {
    self.set = set;
  }

  pub fn with_set(mut self, set: String) -> SwaggerJwkUpdateSetKey {
    self.set = set;
    self
  }

  pub fn set(&self) -> &String {
    &self.set
  }


}



