/* 
 * Hydra OAuth2 & OpenID Connect Server
 *
 * Please refer to the user guide for in-depth documentation: https://ory.gitbooks.io/hydra/content/   Hydra offers OAuth 2.0 and OpenID Connect Core 1.0 capabilities as a service. Hydra is different, because it works with any existing authentication infrastructure, not just LDAP or SAML. By implementing a consent app (works with any programming language) you build a bridge between Hydra and your authentication infrastructure. Hydra is able to securely manage JSON Web Keys, and has a sophisticated policy-based access control you can use if you want to. Hydra is suitable for green- (new) and brownfield (existing) projects. If you are not familiar with OAuth 2.0 and are working on a greenfield project, we recommend evaluating if OAuth 2.0 really serves your purpose. Knowledge of OAuth 2.0 is imperative in understanding what Hydra does and how it works.   The official repository is located at https://github.com/ory/hydra   ### Important REST API Documentation Notes  The swagger generator used to create this documentation does currently not support example responses. To see request and response payloads click on **\"Show JSON schema\"**: ![Enable JSON Schema on Apiary](https://storage.googleapis.com/ory.am/hydra/json-schema.png)   The API documentation always refers to the latest tagged version of ORY Hydra. For previous API documentations, please refer to https://github.com/ory/hydra/blob/<tag-id>/docs/api.swagger.yaml - for example:  0.9.13: https://github.com/ory/hydra/blob/v0.9.13/docs/api.swagger.yaml 0.8.1: https://github.com/ory/hydra/blob/v0.8.1/docs/api.swagger.yaml
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct SwaggeruserinfoResponsePayload {
  /// End-User's birthday, represented as an ISO 8601:2004 [ISO8601‑2004] YYYY-MM-DD format. The year MAY be 0000, indicating that it is omitted. To represent only the year, YYYY format is allowed. Note that depending on the underlying platform's date related function, providing just year can result in varying month and day, so the implementers need to take this factor into account to correctly process the dates.
  #[serde(rename = "birthdate")]
  birthdate: Option<String>,
  /// End-User's preferred e-mail address. Its value MUST conform to the RFC 5322 [RFC5322] addr-spec syntax. The RP MUST NOT rely upon this value being unique, as discussed in Section 5.7.
  #[serde(rename = "email")]
  email: Option<String>,
  /// True if the End-User's e-mail address has been verified; otherwise false. When this Claim Value is true, this means that the OP took affirmative steps to ensure that this e-mail address was controlled by the End-User at the time the verification was performed. The means by which an e-mail address is verified is context-specific, and dependent upon the trust framework or contractual agreements within which the parties are operating.
  #[serde(rename = "email_verified")]
  email_verified: Option<bool>,
  /// Surname(s) or last name(s) of the End-User. Note that in some cultures, people can have multiple family names or no family name; all can be present, with the names being separated by space characters.
  #[serde(rename = "family_name")]
  family_name: Option<String>,
  /// End-User's gender. Values defined by this specification are female and male. Other values MAY be used when neither of the defined values are applicable.
  #[serde(rename = "gender")]
  gender: Option<String>,
  /// Given name(s) or first name(s) of the End-User. Note that in some cultures, people can have multiple given names; all can be present, with the names being separated by space characters.
  #[serde(rename = "given_name")]
  given_name: Option<String>,
  /// End-User's locale, represented as a BCP47 [RFC5646] language tag. This is typically an ISO 639-1 Alpha-2 [ISO639‑1] language code in lowercase and an ISO 3166-1 Alpha-2 [ISO3166‑1] country code in uppercase, separated by a dash. For example, en-US or fr-CA. As a compatibility note, some implementations have used an underscore as the separator rather than a dash, for example, en_US; Relying Parties MAY choose to accept this locale syntax as well.
  #[serde(rename = "locale")]
  locale: Option<String>,
  /// Middle name(s) of the End-User. Note that in some cultures, people can have multiple middle names; all can be present, with the names being separated by space characters. Also note that in some cultures, middle names are not used.
  #[serde(rename = "middle_name")]
  middle_name: Option<String>,
  /// End-User's full name in displayable form including all name parts, possibly including titles and suffixes, ordered according to the End-User's locale and preferences.
  #[serde(rename = "name")]
  name: Option<String>,
  /// Casual name of the End-User that may or may not be the same as the given_name. For instance, a nickname value of Mike might be returned alongside a given_name value of Michael.
  #[serde(rename = "nickname")]
  nickname: Option<String>,
  /// End-User's preferred telephone number. E.164 [E.164] is RECOMMENDED as the format of this Claim, for example, +1 (425) 555-1212 or +56 (2) 687 2400. If the phone number contains an extension, it is RECOMMENDED that the extension be represented using the RFC 3966 [RFC3966] extension syntax, for example, +1 (604) 555-1234;ext=5678.
  #[serde(rename = "phone_number")]
  phone_number: Option<String>,
  /// True if the End-User's phone number has been verified; otherwise false. When this Claim Value is true, this means that the OP took affirmative steps to ensure that this phone number was controlled by the End-User at the time the verification was performed. The means by which a phone number is verified is context-specific, and dependent upon the trust framework or contractual agreements within which the parties are operating. When true, the phone_number Claim MUST be in E.164 format and any extensions MUST be represented in RFC 3966 format.
  #[serde(rename = "phone_number_verified")]
  phone_number_verified: Option<bool>,
  /// URL of the End-User's profile picture. This URL MUST refer to an image file (for example, a PNG, JPEG, or GIF image file), rather than to a Web page containing an image. Note that this URL SHOULD specifically reference a profile photo of the End-User suitable for displaying when describing the End-User, rather than an arbitrary photo taken by the End-User.
  #[serde(rename = "picture")]
  picture: Option<String>,
  /// Non-unique shorthand name by which the End-User wishes to be referred to at the RP, such as janedoe or j.doe. This value MAY be any valid JSON string including special characters such as @, /, or whitespace.
  #[serde(rename = "preferred_username")]
  preferred_username: Option<String>,
  /// URL of the End-User's profile page. The contents of this Web page SHOULD be about the End-User.
  #[serde(rename = "profile")]
  profile: Option<String>,
  /// Subject - Identifier for the End-User at the Issuer.
  #[serde(rename = "sub")]
  sub: Option<String>,
  /// Time the End-User's information was last updated. Its value is a JSON number representing the number of seconds from 1970-01-01T0:0:0Z as measured in UTC until the date/time.
  #[serde(rename = "updated_at")]
  updated_at: Option<i64>,
  /// URL of the End-User's Web page or blog. This Web page SHOULD contain information published by the End-User or an organization that the End-User is affiliated with.
  #[serde(rename = "website")]
  website: Option<String>,
  /// String from zoneinfo [zoneinfo] time zone database representing the End-User's time zone. For example, Europe/Paris or America/Los_Angeles.
  #[serde(rename = "zoneinfo")]
  zoneinfo: Option<String>
}

impl SwaggeruserinfoResponsePayload {
  pub fn new() -> SwaggeruserinfoResponsePayload {
    SwaggeruserinfoResponsePayload {
      birthdate: None,
      email: None,
      email_verified: None,
      family_name: None,
      gender: None,
      given_name: None,
      locale: None,
      middle_name: None,
      name: None,
      nickname: None,
      phone_number: None,
      phone_number_verified: None,
      picture: None,
      preferred_username: None,
      profile: None,
      sub: None,
      updated_at: None,
      website: None,
      zoneinfo: None
    }
  }

  pub fn set_birthdate(&mut self, birthdate: String) {
    self.birthdate = Some(birthdate);
  }

  pub fn with_birthdate(mut self, birthdate: String) -> SwaggeruserinfoResponsePayload {
    self.birthdate = Some(birthdate);
    self
  }

  pub fn birthdate(&self) -> Option<&String> {
    self.birthdate.as_ref()
  }

  pub fn reset_birthdate(&mut self) {
    self.birthdate = None;
  }

  pub fn set_email(&mut self, email: String) {
    self.email = Some(email);
  }

  pub fn with_email(mut self, email: String) -> SwaggeruserinfoResponsePayload {
    self.email = Some(email);
    self
  }

  pub fn email(&self) -> Option<&String> {
    self.email.as_ref()
  }

  pub fn reset_email(&mut self) {
    self.email = None;
  }

  pub fn set_email_verified(&mut self, email_verified: bool) {
    self.email_verified = Some(email_verified);
  }

  pub fn with_email_verified(mut self, email_verified: bool) -> SwaggeruserinfoResponsePayload {
    self.email_verified = Some(email_verified);
    self
  }

  pub fn email_verified(&self) -> Option<&bool> {
    self.email_verified.as_ref()
  }

  pub fn reset_email_verified(&mut self) {
    self.email_verified = None;
  }

  pub fn set_family_name(&mut self, family_name: String) {
    self.family_name = Some(family_name);
  }

  pub fn with_family_name(mut self, family_name: String) -> SwaggeruserinfoResponsePayload {
    self.family_name = Some(family_name);
    self
  }

  pub fn family_name(&self) -> Option<&String> {
    self.family_name.as_ref()
  }

  pub fn reset_family_name(&mut self) {
    self.family_name = None;
  }

  pub fn set_gender(&mut self, gender: String) {
    self.gender = Some(gender);
  }

  pub fn with_gender(mut self, gender: String) -> SwaggeruserinfoResponsePayload {
    self.gender = Some(gender);
    self
  }

  pub fn gender(&self) -> Option<&String> {
    self.gender.as_ref()
  }

  pub fn reset_gender(&mut self) {
    self.gender = None;
  }

  pub fn set_given_name(&mut self, given_name: String) {
    self.given_name = Some(given_name);
  }

  pub fn with_given_name(mut self, given_name: String) -> SwaggeruserinfoResponsePayload {
    self.given_name = Some(given_name);
    self
  }

  pub fn given_name(&self) -> Option<&String> {
    self.given_name.as_ref()
  }

  pub fn reset_given_name(&mut self) {
    self.given_name = None;
  }

  pub fn set_locale(&mut self, locale: String) {
    self.locale = Some(locale);
  }

  pub fn with_locale(mut self, locale: String) -> SwaggeruserinfoResponsePayload {
    self.locale = Some(locale);
    self
  }

  pub fn locale(&self) -> Option<&String> {
    self.locale.as_ref()
  }

  pub fn reset_locale(&mut self) {
    self.locale = None;
  }

  pub fn set_middle_name(&mut self, middle_name: String) {
    self.middle_name = Some(middle_name);
  }

  pub fn with_middle_name(mut self, middle_name: String) -> SwaggeruserinfoResponsePayload {
    self.middle_name = Some(middle_name);
    self
  }

  pub fn middle_name(&self) -> Option<&String> {
    self.middle_name.as_ref()
  }

  pub fn reset_middle_name(&mut self) {
    self.middle_name = None;
  }

  pub fn set_name(&mut self, name: String) {
    self.name = Some(name);
  }

  pub fn with_name(mut self, name: String) -> SwaggeruserinfoResponsePayload {
    self.name = Some(name);
    self
  }

  pub fn name(&self) -> Option<&String> {
    self.name.as_ref()
  }

  pub fn reset_name(&mut self) {
    self.name = None;
  }

  pub fn set_nickname(&mut self, nickname: String) {
    self.nickname = Some(nickname);
  }

  pub fn with_nickname(mut self, nickname: String) -> SwaggeruserinfoResponsePayload {
    self.nickname = Some(nickname);
    self
  }

  pub fn nickname(&self) -> Option<&String> {
    self.nickname.as_ref()
  }

  pub fn reset_nickname(&mut self) {
    self.nickname = None;
  }

  pub fn set_phone_number(&mut self, phone_number: String) {
    self.phone_number = Some(phone_number);
  }

  pub fn with_phone_number(mut self, phone_number: String) -> SwaggeruserinfoResponsePayload {
    self.phone_number = Some(phone_number);
    self
  }

  pub fn phone_number(&self) -> Option<&String> {
    self.phone_number.as_ref()
  }

  pub fn reset_phone_number(&mut self) {
    self.phone_number = None;
  }

  pub fn set_phone_number_verified(&mut self, phone_number_verified: bool) {
    self.phone_number_verified = Some(phone_number_verified);
  }

  pub fn with_phone_number_verified(mut self, phone_number_verified: bool) -> SwaggeruserinfoResponsePayload {
    self.phone_number_verified = Some(phone_number_verified);
    self
  }

  pub fn phone_number_verified(&self) -> Option<&bool> {
    self.phone_number_verified.as_ref()
  }

  pub fn reset_phone_number_verified(&mut self) {
    self.phone_number_verified = None;
  }

  pub fn set_picture(&mut self, picture: String) {
    self.picture = Some(picture);
  }

  pub fn with_picture(mut self, picture: String) -> SwaggeruserinfoResponsePayload {
    self.picture = Some(picture);
    self
  }

  pub fn picture(&self) -> Option<&String> {
    self.picture.as_ref()
  }

  pub fn reset_picture(&mut self) {
    self.picture = None;
  }

  pub fn set_preferred_username(&mut self, preferred_username: String) {
    self.preferred_username = Some(preferred_username);
  }

  pub fn with_preferred_username(mut self, preferred_username: String) -> SwaggeruserinfoResponsePayload {
    self.preferred_username = Some(preferred_username);
    self
  }

  pub fn preferred_username(&self) -> Option<&String> {
    self.preferred_username.as_ref()
  }

  pub fn reset_preferred_username(&mut self) {
    self.preferred_username = None;
  }

  pub fn set_profile(&mut self, profile: String) {
    self.profile = Some(profile);
  }

  pub fn with_profile(mut self, profile: String) -> SwaggeruserinfoResponsePayload {
    self.profile = Some(profile);
    self
  }

  pub fn profile(&self) -> Option<&String> {
    self.profile.as_ref()
  }

  pub fn reset_profile(&mut self) {
    self.profile = None;
  }

  pub fn set_sub(&mut self, sub: String) {
    self.sub = Some(sub);
  }

  pub fn with_sub(mut self, sub: String) -> SwaggeruserinfoResponsePayload {
    self.sub = Some(sub);
    self
  }

  pub fn sub(&self) -> Option<&String> {
    self.sub.as_ref()
  }

  pub fn reset_sub(&mut self) {
    self.sub = None;
  }

  pub fn set_updated_at(&mut self, updated_at: i64) {
    self.updated_at = Some(updated_at);
  }

  pub fn with_updated_at(mut self, updated_at: i64) -> SwaggeruserinfoResponsePayload {
    self.updated_at = Some(updated_at);
    self
  }

  pub fn updated_at(&self) -> Option<&i64> {
    self.updated_at.as_ref()
  }

  pub fn reset_updated_at(&mut self) {
    self.updated_at = None;
  }

  pub fn set_website(&mut self, website: String) {
    self.website = Some(website);
  }

  pub fn with_website(mut self, website: String) -> SwaggeruserinfoResponsePayload {
    self.website = Some(website);
    self
  }

  pub fn website(&self) -> Option<&String> {
    self.website.as_ref()
  }

  pub fn reset_website(&mut self) {
    self.website = None;
  }

  pub fn set_zoneinfo(&mut self, zoneinfo: String) {
    self.zoneinfo = Some(zoneinfo);
  }

  pub fn with_zoneinfo(mut self, zoneinfo: String) -> SwaggeruserinfoResponsePayload {
    self.zoneinfo = Some(zoneinfo);
    self
  }

  pub fn zoneinfo(&self) -> Option<&String> {
    self.zoneinfo.as_ref()
  }

  pub fn reset_zoneinfo(&mut self) {
    self.zoneinfo = None;
  }

}



