/* 
 * ORY Hydra - Cloud Native OAuth 2.0 and OpenID Connect Server
 *
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here. Keep in mind that this document reflects the latest branch, always. Support for versioned documentation is coming in the future.
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct SwaggerListPolicyParameters {
  /// The maximum amount of policies returned. in: query
  #[serde(rename = "limit")]
  limit: Option<i64>,
  /// The offset from where to start looking. in: query
  #[serde(rename = "offset")]
  offset: Option<i64>
}

impl SwaggerListPolicyParameters {
  pub fn new() -> SwaggerListPolicyParameters {
    SwaggerListPolicyParameters {
      limit: None,
      offset: None
    }
  }

  pub fn set_limit(&mut self, limit: i64) {
    self.limit = Some(limit);
  }

  pub fn with_limit(mut self, limit: i64) -> SwaggerListPolicyParameters {
    self.limit = Some(limit);
    self
  }

  pub fn limit(&self) -> Option<&i64> {
    self.limit.as_ref()
  }

  pub fn reset_limit(&mut self) {
    self.limit = None;
  }

  pub fn set_offset(&mut self, offset: i64) {
    self.offset = Some(offset);
  }

  pub fn with_offset(mut self, offset: i64) -> SwaggerListPolicyParameters {
    self.offset = Some(offset);
    self
  }

  pub fn offset(&self) -> Option<&i64> {
    self.offset.as_ref()
  }

  pub fn reset_offset(&mut self) {
    self.offset = None;
  }

}



